### ISSUE TITLE
Regarding two patients taking appointment to doctor at the same time.

### ISSUE THREAD

**Issue by Poojal04** [devansh83/DocuMed#93]
There is no error message displayed regarding appointment at the same time to a particular doctor.Patient 1 and Patient 2 can take appointment from a particular doctor at the same time.
Bug Details:Logged in as patient 1 and patient 2.Both the patients share the document to a particular doctor. The doctor is able to give appointments to both patients at the same time which is not possible in real time.

**Comment by Tanush247** [comment]
The feature has been successfully implemented. Similar to real-life scenarios, we've standardized appointments to be 30 minutes in length. If any new appointment overlaps within 30 minutes of an existing appointment, an error message stating _'Another appointment already exists within 30 minutes of this time'_ will be displayed.

I am closing this issue for now. Please feel free to reopen it if the problem persists.
