### ISSUE TITLE
Regarding scheduling appointment on days which are not working for doctor

### ISSUE THREAD

**Issue by Poojal04** [devansh83/DocuMed#94]
The schedule day feature is just a feature which is not being used in scheduling of the appointment. Like if I schedule appointment on Sunday but it is not working day for doctor then also appointment can be done.

**Comment by Tanush247** [comment]
"The feature has been updated. Initially, when a doctor registers, all days are marked as working days. However, using the update profile feature, the doctor can now modify the working days. If a valid follow-up date is entered that does not fall on a valid working day, an error message stating _'Appointment date does not fall on a working day for the doctor'_ will be displayed.

I am closing this issue for now. Please feel free to reopen it if the problem persists."
